input {
  file {
    path => "/var/lib/docker/containers/944e31a3f858a75f35abccd66c5c844ff6aeda64b630658bcfb1b056db7d2ac1/944e31a3f858a75f35abccd66c5c844ff6aeda64b630658bcfb1b056db7d2ac1-json.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  json {
    source => "log"
    target => "app_log"
  }

  date {
    match => [ "[app_log][time]", "ISO8601" ]
    target => "@timestamp"
  }

  mutate {
    add_field => {
      "service" => "payment-gateway"
      "container" => "pay-gate-app"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "payment-gateway-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}